README.md

Corrected "[Intsall]" to "[Install]" in [README.md].
This pull request addresses a minor typo found in repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.

Docs: Typo fix

---

README.md

**Description:**  
- Added new MemFree feature descriptions and capabilities.
- Updated deployment guides for Zeabur, Vercel, and Fly.io.
- Enhanced sections on MemFree's value propositions and tech stack.
This PR enhances the README file with clearer instructions, new features, and updated deployment steps.

Update README: New Features, Deployment Guides Enhancements

---

Contribution.md

I have added contribution.md file which has all necessary information needed for doing any contribution in this repo.
kindly review my PR.

Resolved issue#10 by adding Contribution.md file

---

README.md

Added Contributors images in readme

---

.github/workflows/greetings.yml
README.md

Closes #34 
You can change the greeting message for issues and pr to your liking.

Added Automated Greeting for Issues and Pull Requests

---

README.md

Added github star history to README.md file

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_update.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/autocomment-issue-closed.yml
.github/workflows/autocomment-issue.yml
.github/workflows/autocomment-pr-merge.yml
.github/workflows/autocomment-pr-raise.yml
README.md

Issue template

---

.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Added Enhancement Issue template and modified the Feature Request Template to differentiate between both.
Closes #43

Added enhancement issue template

---

README/README-ZH.md

Feat: Added chinese language readme file.

---

README.md
README_DE.md
README_ES.md
README_FR.md
README_ZH.md

- Closes #123
- Fixes #456
1. Step 1
2. Step 2
3. Step 3

Added readme file for other lang

---

README.md
README_DE.md
README_ES.md
README_FR.md
README_JA.md
README_ZH.md

- Closes #123
- Fixes #456
1. Step 1
2. Step 2
3. Step 3

feat: Added japanese readme file.

---

frontend/components/code/toolbar.tsx
frontend/components/layout/feature-sections.tsx
frontend/components/ui/pagination.tsx
frontend/components/ui/separator.tsx

Resolve compiler warnings in multiple files
`frontend/components/code/toolbar.tsx`
`frontend/components/layout/feature-sections.tsx`
`frontend/components/ui/pagination.tsx`
`frontend/components/ui/separator.tsx`
#11 
NA
Would like to get your thoughts, if this is on the right track planning to fix few more warnings.

fix: resolve compiler warnings in multiple files

---

frontend/app/[locale]/(search)/generate-ui/page.tsx
frontend/components/code/code-viewer.tsx
frontend/components/code/preview.tsx
frontend/components/layout/wall-of-love.tsx
frontend/components/search/ui-demo-gallery.tsx
frontend/components/ui/radio-group.tsx
frontend/components/ui/slider.tsx

Resolve compiler warnings in various files for improving the build performance and renamed `ui-demo-gallery` file.
`frontend/components/code/code-viewer.tsx`
`frontend/components/code/preview.tsx`
`frontend/components/layout/wall-of-love.tsx`
`frontend/components/search/ui-demo-gallery.tsx`
`frontend/components/ui/radio-group.tsx`
`frontend/components/ui/slider.tsx`
#11 

refactor: address compiler warnings and improve file naming

---

CODE_OF_CONDUCT.md

- Closes #123
- Fixes #456
1. Step 1
2. Step 2
3. Step 3

Added code of conduct md file

---

frontend/app/api/one-tap-login/route.ts
frontend/app/api/webhooks/stripe/route.ts
frontend/auth.ts
frontend/config.ts
frontend/hooks/use-one-tap.ts
frontend/hooks/use-upload-file.ts
frontend/lib/db.ts
frontend/lib/env.ts
frontend/lib/log.ts
frontend/lib/rerank.ts
frontend/lib/search/exa.ts
frontend/lib/search/vector.ts
frontend/lib/store/search.ts
frontend/lib/stripe.ts
frontend/lib/utils.ts

Unified all the environment variables into the env.ts so we would not have to go into individual files to enter the env variables
-Closes #69 
1. Step 1
2. Step 2
3. Step 3

Unified all front-end environment variables into the env.ts file

---

SECURITY.md

This pull request includes the addition of a `SECURITY.md` file to the root directory of the repository. This file establishes a security policy for the project, guiding users and contributors on how to report vulnerabilities in a secure and responsible manner. The purpose is to ensure that any security issues are properly addressed while maintaining confidentiality and protecting the project.
- Closes #53 
1. Check that the `SECURITY.md` file is correctly placed in the root directory.
2. Review the file contents to ensure the security policy is clear and the provided link to the GitHub issues section works properly.
3. Verify that the policy outlines a proper procedure for reporting vulnerabilities without disclosing sensitive information.
N/A (No visual modifications made)
This update …

Security Policy file 

---

frontend/jest.config.js
frontend/lib/store/tests/README.md
frontend/lib/store/tests/local-limit.test.ts
frontend/lib/store/tests/setupTests.ts
frontend/package.json
frontend/tsconfig.json

added jest test suite for local-limit
- Closes #58 
First check out the README.md in lib/store/tests
1. Step 1 - npm install (or npm install --legacy-peer-deps)
2. Step 2 -  npm test
3. Step 3 - check the results

added jest test suite for local-limit

---

README.md

Add bash commands for bun not found error while setting up the project.
#77 [Documentation Update]: Incomplete installation guide for bun while setting up the project. 
1. Step 1
2. Step 2
3. Step 3

Add bash commands for bun not found error.

---

frontend/components/sidebar/sidebar-item.tsx
frontend/lib/utils.ts

Optimized the time display of historical messages based on the created time.
- Fixes #89 
1. Step 1
2. Step 2
3. Step 3

added optimized time display format of historical messages

---

frontend/lib/store/tests/TESTING_GUIDELINES.md
frontend/lib/utils.ts

The testing guideline is under frontend/lib/store/tests.
- Closes #86 
1. Step 1
2. Step 2
3. Step 3

added testing guideline and example

---

frontend/lib/search/search.ts

This PR refactors the search engine selection logic for better readability, flexibility, and maintainability. Key improvements include:
- Flexible Category Matching: Replaced the switch statement with .includes() to support multiple category checks and avoid index errors.
- Default Parameters: Added a default empty object for SearchOptions to prevent runtime errors.
- Code Reuse: Used the spread operator (...options) to ensure options are consistently passed across search engines.
- Improved Readability: Added JSDoc-style comments to clarify the purpose of key functions.
These changes make the code more robust, easier to extend, and maintain. The logic remains functionally identical with better error handling and support for additional categories in the future.

Refactor Search Engine Selection Logic and Improve Code Flexibility

---

frontend/lib/search/vector.ts

This PR optimizes the VectorSearch class by improving code readability and maintainability. Key changes include:
Introduced a private getter for URL construction.
Used static constants for distance values.
Replaced map with forEach for array population.
Streamlined error handling.

Refactor VectorSearch Class

---

frontend/components/code/preview.tsx

Error Handling Component: ErrorDisplay separates out error display logic, simplifying the Preview component.
Error Context: Improved logging with clearer messages for error locations.
Naming Correction: Corrected isDaskMode to isDarkMode.
Optimized Dependency Arrays: Ensured minimal dependency arrays for useMemo and useCallback functions.

Enhanced Error Handling and naming correction

---

frontend/lib/search/vector.ts

This PR optimizes the VectorSearch class by improving code readability and maintainability. Key changes include:
Introduced a private getter for URL construction.
Used static constants for distance values.
Replaced map with forEach for array population.
Streamlined error handling.

Optimize VectorSearch Class Implementation

---

frontend/lib/index/compact.ts

- Consolidated headers for reuse and to avoid recomputation in case of multiple calls.
- Fetches the error body content in cases of failed requests, which can give more context.
- Clear Error Messages.

refactor: refactored compact.ts

---

frontend/hooks/use-one-tap.ts

This PR refactors the useOneTapSignin hook to streamline the Google One Tap sign-in flow. Key improvements include optimizing the async handling of the oneTap function, reducing redundant code, and enhancing readability. The changes ensure that isLoading state is managed effectively and that unnecessary checks are removed. This refactor should provide a smoother, more maintainable codebase for handling Google One Tap sign-ins.

refactor: improve async handling

---

frontend/lib/search/search.ts

- Simplified getSearchEngine Logic

refactor: refactored search.ts

---

frontend/lib/tools/hacker-news.ts

This PR removes unnecessary object spreading to improve performance

perf: remove unnecessary object spread

---

frontend/actions/open-customer-portal.ts

This PR removes redundant error handling inside `open-customer-portal`.

refactor(open-customer-portal): remove redundant error handling

---

frontend/app/[locale]/(docs)/docs/[[...slug]]/page.tsx

Fixes mobile visibility issues for the 'AI Generate UI Now' button
- Fixes #126 
1. Step 1
2. Step 2
3. Step 3

fix: improve mobile visibility for AI Generate UI Now button

---

README.md

Closes #16: Support one click deploy on Railway
1. Step 1
2. Step 2
3. Step 3

Docs: Add one click deploy for railway.

---

.github/workflows/readme.yml

removed unnecessary branches from workflow.
- Fixes #113: remove redundant branches from readme.yml file.
- remove redundant branches from readme.yml file.
1. Step 1
2. Step 2
3. Step 3

removed unnecessary branches for work flow.

---

frontend/app/[locale]/(search)/settings/page.tsx

Fix sidebar bug
1. Goto [link](https://www.memfree.me/settings)

scrollbar showing in middle of the settings page
